Setup the base of project based on FastApi
openfoodfacts/facets-knowledge-panels pull request #4
Opened 2022-07-06 11:56 UTC by sumit-158

### What
- Initializing the project based on FastApi currently its shows "helloworld" 
- Also docker-compose 

### Fixes bug(s)
- #1

2022-07-06 14:53 UTC, sumit-158 commented
@alexgarel  pytest is skipping with this message 
![image](https://user-images.githubusercontent.com/96618001/177579816-17dad452-822f-4b2f-b02e-6f1b7df0101a.png)

2022-07-06 14:59 UTC, sumit-158 commented
> @alexgarel pytest is skipping with this message 

Sloved!

2022-07-06 15:43 UTC, alexgarel reviewed
TODO:
- move test_main.py to its own directory
- change the current description for it would only solve issue #1 yet (and it's better to have separate PRs if possible)
- update README to explain how to setup the project and run the tests

2022-07-07 07:56 UTC, alexgarel commented on README.md
> +- If desired, apps can decide to use new product attributes added on the server without requiring app changes
This is more the why of knowledge panels. (not specific to facets)

But the examples that are given are not consistent with facet.

I would rather say.:
```suggestion
Provides applications with a set of informative or actionable items which are contextual to a specific facet.

The primary goal is to allow high level contributions by users that maybe interested in a particular subset of the database, like a particular food category or a brand, a location, etc...

We reuse the knowledge panel format, which remove the need for the application to change as the server side code change, or to implement specific business logic.

```

2022-07-07 08:02 UTC, alexgarel requested changes
Hi @sumit-158 , good job.

Small changes requested.
+ remember that this only fixes first bug. Please remove the other two from your comment.

2022-07-07 08:02 UTC, alexgarel commented on README.md
> +```
This is true if you use "virtual env" if you use docker you have to launch with docker-compose.
````suggestion
### docker setup
```
docker-compose run --rm facets-api pytest tests
```

### virtual env setup
- Checkout `tests` directory
```
pytest 
```
````

2022-07-07 10:04 UTC, sumit-158 commented
> Small changes requested.
> 
> * remember that this only fixes first bug. Please remove the other two from your comment.

Done , I hope everything is good now :)

2022-07-07 12:06 UTC, sumit-158 commented
> * remember that this only fixes first bug. Please remove the other two from your comment.

but, @alexgarel it also return hunger game KP as you shows in ticket #3

2022-07-07 17:05 UTC, alexgarel commented on app/main.py
> +                        "level": "questions",
I don't think this two values are ok, but it's not blocking right now :-)

2022-07-07 17:12 UTC, alexgarel approved these changes
Perfect @sumit-158  !

I installed and run locally :-) It worked like a charm.

2022-07-07 17:13 UTC, merged