feat: Adding a knowledge panel for Hunger Games
openfoodfacts/facets-knowledge-panels pull request #8
Opened 2022-07-12 11:26 UTC by sumit-158

### What
- Implementing simple hunger game KP
- Add tests 

### Fixes bug(s)
- #3

2022-07-13 08:15 UTC, alexgarel commented on app/main.py
> +    return {"knowledge_panels": []}
the idea is more:

```python
panels = []
if facet_name in Hunger_game_filter:
  panels.append(hunger_game_kp(....))
return {"knowledge_panels": panels}
```

but I would better have the hunger_game_kp in a knowledge_panels.py

2022-07-13 08:19 UTC, alexgarel commented on app/models.py
> +class Hunger_game_filter(str, Enum):
```suggestion
class HungerGameFilter(str, Enum):
```

2022-07-13 08:19 UTC, alexgarel commented on app/models.py
>  class Facetname(str, Enum):
```suggestion
class FacetName(str, Enum):
```

2022-07-13 14:35 UTC, alexgarel requested changes
Still something to fix.

You should add a test_knowledge_panels.py where you test hunger_game_kp with following scenario:
- asking for a category with a country
- asking for a brand with a country
- asking a category without a country
- asking question for a country only

Also you should add integration test for the knowledge_panel api point  to test_main.py:

- asking for a category
- asking for a category with a country parameter
- asking for a allergen (should return an empty list of knowledge panel)

2022-07-13 14:35 UTC, alexgarel commented on app/main.py
> +                      value=facet_value, country=country))
Maybe you should also manage the case where facet_name == "country". (It's cool however to also have the specific country argument), that should be equivalent to setting country. (the facet should have priority over country parameter)

2022-07-13 14:35 UTC, alexgarel commented on app/main.py
> +            "Sorry! hunger game knowlege panel for this facet isn't available right now")
you should not do that because it brakes the API, just ignore this case.

```suggestion
```

2022-07-13 14:35 UTC, alexgarel commented on app/models.py
> +        return list(map(lambda c: c.value, Facetname))
More pythonic + correct Facetname --> FacetName:

```suggestion
        return [c.value for c in  FacetName]
```

2022-07-13 14:35 UTC, alexgarel commented on app/models.py
> +        return list(map(lambda c: c.value, HungerGameFilter))
```suggestion
        return [c.value for c in HungerGameFilter]
```

2022-07-13 14:35 UTC, alexgarel commented on tests/test_main.py
> +    return response.json()
you should just remove this test.
```suggestion
```

2022-07-13 15:34 UTC, sumit-158 commented
> Still something to fix.
> 
> You should add a test_knowledge_panels.py
> Also you should add integration test for the knowledge_panel api point to test_main.py:

Sorry! @alexgarel I forgot about tests and asks for review

2022-07-13 17:02 UTC, alexgarel commented on app/knowledge_panels.py
> +        html = f"'<p><a href=\'https://hunger.openfoodfacts.org/?type={hunger_game_filter}&value_tag={value}&country={country}\'></a></p>\n'"
This code should be far more readable ;-)

Please use urllib.parse.urlencode and treat country and value separately !

2022-07-14 17:07 UTC, sumit-158 commented on tests/test_main.py
> +    assert knowledge_panel(facet_name="category") == {"knowledge_panels": [{'hunger-game': {'elements': [{'element_type': 'text', 'text_element': {
Solved :)

2022-07-15 08:28 UTC, alexgarel commented on app/knowledge_panels.py
> +        html = f"<p><a href='{baseUrl}{hunger_game_filter}&{valueQuery}&{countryQuery}'></a></p>\n"
You didn't get it about urlencode ;-) the idea is to de-correlate both argument handling, by treating them separately.
Also your link does not have a text so would be invisible to users.
Also note that you should alway use `== None` but instead use `is None`. (same for `!= None` ==> `is not None`.

Here is how you can separate problems:

```suggestion
    query = {}
    description = ""
    if hunger_game_filter == "country":
        # superseed country parameter
        country = value
        # and do not use facet
        hunger_game_filter = value = None
    if country is not None:
        query["country"] = country
        description = country
    if value_tag is not None:
        query["type"] = hunger_game_filter
        query["value_tag"] = value
        description = f"{value} {hunger_game_filter}"
    questions_url = "https://hunger.openfoodfacts.org/"
    if query:
        questions_url += f"?{urlencode(query)}"
    description = f"Answer robotoff questions about {description}"
    html = f"<p><a href='{questions_url}'>{description}</a></p>\n"
```

2022-07-15 08:29 UTC, alexgarel commented on app/models.py
> +    product_weight = "product_weight"
you should add country, because this is a valid facet (it will superseed country parameter)

2022-07-15 08:30 UTC, alexgarel commented on app/knowledge_panels.py
> +        html = f"<p><a href='{baseUrl}{hunger_game_filter}&{valueQuery}&{countryQuery}'></a></p>\n"
I forgot to add that you didn't handle using country facet… the above code does this.

2022-07-15 08:32 UTC, alexgarel commented on app/knowledge_panels.py
> +        html = f"<p><a href='{baseUrl}{hunger_game_filter}&{valueQuery}&{countryQuery}'></a></p>\n"
As I see that in your test you even test hunger_game_filter alone, I have just updated code suggestion to enable that.

2022-07-15 08:40 UTC, alexgarel requested changes
You've done significant progress @sumit-158 

Find all my comments… we are almost there.

2022-07-15 08:40 UTC, alexgarel commented on tests/test_main.py
> +    assert response.status_code == 422
Please also assert the content of response. (should be an empty list of knowledge panels)

2022-07-15 08:40 UTC, alexgarel commented on tests/test_main.py
> +    }
As you already tested the hunger_game_kp function quite heavily, it's sufficient here to have a test including a facet_name, a facet_value and a country.

Note: the main usage will be facet_name + facet_value (not facet_name alone). So this is better to test this one.

2022-07-15 11:11 UTC, sumit-158 commented
@alexgarel the current url in api look like this `https://hunger.openfoodfacts.org/?type=category&value_tag=beer` but the hunger game url look like this `https://hunger.openfoodfacts.org/questions?type=country` what your thought ?

2022-07-15 15:00 UTC, teolemon commented
https://hunger.openfoodfacts.org/?type=category&value_tag=en:beers

2022-07-15 15:15 UTC, alexgarel commented
> @alexgarel the current url in api look like this https://hunger.openfoodfacts.org/?type=category&value_tag=beer but the hunger game url look like this https://hunger.openfoodfacts.org/questions?type=country what your thought ?

Yup, I think I forgot the /questions part ! 
You can fix it :-)

2022-07-15 16:24 UTC, alexgarel commented on tests/test_knowledge_panels.py
> +    }
I think we can skip those tests, which we already did for category (the test below is good enough to test the brand facet exists).

2022-07-15 16:26 UTC, alexgarel approved these changes
Ok, I propose to remove 4 tests, as they seems a bit too much to me.

But otherwise it's all ok :-)

I let you merge when you are ready.

2022-07-15 16:40 UTC, merged